/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arztpraxis;

/**
 *
 * @author coafin
 */
public class Formular extends javax.swing.JFrame {

    Wartezimmer wartezimmer;

    public Formular() {
        wartezimmer = new Wartezimmer();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        titleLable = new javax.swing.JLabel();
        patientInputPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        kundennummerLable = new javax.swing.JLabel();
        genderLable = new javax.swing.JLabel();
        prioLable = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        kundenNummerTextField = new javax.swing.JTextField();
        genderTextField = new javax.swing.JTextField();
        prioCheckBox = new javax.swing.JCheckBox();
        controlPanel = new javax.swing.JPanel();
        anstellenButton = new javax.swing.JButton();
        naechsterButton = new javax.swing.JButton();
        patientPanel = new javax.swing.JPanel();
        patientTextField = new javax.swing.JTextField();
        wartezimmerPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        wartezimmerTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 300));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        titleLable.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        titleLable.setText("Arztpraxis:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(titleLable, gridBagConstraints);

        patientInputPanel.setLayout(new java.awt.GridLayout(0, 4));

        nameLabel.setText("Name:");
        patientInputPanel.add(nameLabel);

        kundennummerLable.setText("Kundennummer:");
        patientInputPanel.add(kundennummerLable);

        genderLable.setText("Geschlecht:");
        patientInputPanel.add(genderLable);

        prioLable.setText("Prioritaet:");
        patientInputPanel.add(prioLable);
        patientInputPanel.add(nameTextField);
        patientInputPanel.add(kundenNummerTextField);
        patientInputPanel.add(genderTextField);

        prioCheckBox.setText("Prioritaet");
        patientInputPanel.add(prioCheckBox);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(patientInputPanel, gridBagConstraints);

        controlPanel.setLayout(new java.awt.GridLayout(1, 0));

        anstellenButton.setText("Anstellen");
        anstellenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anstellenButtonActionPerformed(evt);
            }
        });
        controlPanel.add(anstellenButton);

        naechsterButton.setText("Patient holen");
        naechsterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naechsterButtonActionPerformed(evt);
            }
        });
        controlPanel.add(naechsterButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(controlPanel, gridBagConstraints);

        patientPanel.setLayout(new java.awt.GridLayout(1, 1));
        patientPanel.add(patientTextField);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(patientPanel, gridBagConstraints);

        wartezimmerPanel.setLayout(new java.awt.GridLayout(1, 0));

        wartezimmerTextArea.setEditable(false);
        wartezimmerTextArea.setColumns(20);
        wartezimmerTextArea.setRows(5);
        jScrollPane1.setViewportView(wartezimmerTextArea);

        wartezimmerPanel.add(jScrollPane1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(wartezimmerPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anstellenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anstellenButtonActionPerformed
        String name = nameTextField.getText();
        String kundenNummerT = kundenNummerTextField.getText();
        int kundenNummer = Integer.parseInt(kundenNummerT);
        String geschlecht = genderTextField.getText();
        boolean prio = prioCheckBox.isSelected();

        Patient patient = new Patient(name, kundenNummer, geschlecht, prio);
        wartezimmer.anstellen(patient);
        updateWartezimmer();
    }//GEN-LAST:event_anstellenButtonActionPerformed

    private void naechsterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naechsterButtonActionPerformed
        Patient patient = wartezimmer.naechsterBitte();
        patientTextField.setText(patient.toString());
        updateWartezimmer();
    }//GEN-LAST:event_naechsterButtonActionPerformed

    private void updateWartezimmer() {
        wartezimmerTextArea.setText(wartezimmer.toString());
    }

    private void clearInput() {
        nameTextField.setText("");
        kundenNummerTextField.setText("");
        genderTextField.setText("");
        prioCheckBox.setSelected(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anstellenButton;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel genderLable;
    private javax.swing.JTextField genderTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kundenNummerTextField;
    private javax.swing.JLabel kundennummerLable;
    private javax.swing.JButton naechsterButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JPanel patientInputPanel;
    private javax.swing.JPanel patientPanel;
    private javax.swing.JTextField patientTextField;
    private javax.swing.JCheckBox prioCheckBox;
    private javax.swing.JLabel prioLable;
    private javax.swing.JLabel titleLable;
    private javax.swing.JPanel wartezimmerPanel;
    private javax.swing.JTextArea wartezimmerTextArea;
    // End of variables declaration//GEN-END:variables
}
