/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sortieren;

/**
 * ***********************************************
 *** OOP Sortieren
 *
 ***
 *** @author Harald Neubeck, Paderborn ** ** @version 06.09.2015 ***
 * ***********************************************
 */
public class Formular extends javax.swing.JFrame {

    private Sortieren sortieren;

    /**
     * Creates new form Formular
     */
    public Formular() {
        initComponents();
        sortieren = new Sortieren();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtErzeugen = new javax.swing.JButton();
        TfGrösse = new javax.swing.JTextField();
        LbAusgabe = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BtSelectionsort = new javax.swing.JButton();
        BtInsertionsort = new javax.swing.JButton();
        BtBubblesort = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtErzeugen.setText("Erzeugen");
        BtErzeugen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtErzeugenActionPerformed(evt);
            }
        });

        LbAusgabe.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Feldgrösse:");

        BtSelectionsort.setText("Selectionsort");
        BtSelectionsort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSelectionsortActionPerformed(evt);
            }
        });

        BtInsertionsort.setText("Insertionsort");
        BtInsertionsort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtInsertionsortActionPerformed(evt);
            }
        });

        BtBubblesort.setText("Bubblesort");
        BtBubblesort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBubblesortActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel2.setText("Sortieralgorithmen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LbAusgabe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtSelectionsort)
                                .addGap(18, 18, 18)
                                .addComponent(BtInsertionsort)
                                .addGap(18, 18, 18)
                                .addComponent(BtBubblesort))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TfGrösse, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtErzeugen)))
                        .addGap(0, 95, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbAusgabe, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfGrösse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtErzeugen)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtSelectionsort)
                    .addComponent(BtInsertionsort)
                    .addComponent(BtBubblesort))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtErzeugenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtErzeugenActionPerformed
        String grösseStr;
        int grösse;
        grösseStr = TfGrösse.getText();
        grösse = Integer.parseInt(grösseStr);
        sortieren.fillArray(grösse);
        LbAusgabe.setText(sortieren.toString());
    }//GEN-LAST:event_BtErzeugenActionPerformed

    private void BtSelectionsortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSelectionsortActionPerformed
        sortieren.selectionsort();
        LbAusgabe.setText(sortieren.toString());
    }//GEN-LAST:event_BtSelectionsortActionPerformed

    private void BtBubblesortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBubblesortActionPerformed
        sortieren.bubblesort();
        LbAusgabe.setText(sortieren.toString());
    }//GEN-LAST:event_BtBubblesortActionPerformed

    private void BtInsertionsortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtInsertionsortActionPerformed
        sortieren.insertionsort();
        LbAusgabe.setText(sortieren.toString());
    }//GEN-LAST:event_BtInsertionsortActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtBubblesort;
    private javax.swing.JButton BtErzeugen;
    private javax.swing.JButton BtInsertionsort;
    private javax.swing.JButton BtSelectionsort;
    private javax.swing.JLabel LbAusgabe;
    private javax.swing.JTextField TfGrösse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
