package türmevonhanoi;

import java.util.HashMap;

public class Formular extends javax.swing.JFrame {

    public HashMap<String, String> tuerme;

    public Formular() {
        initComponents();
        tuerme = new HashMap<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TfZahl = new javax.swing.JTextField();
        TfStart = new javax.swing.JTextField();
        TfMitte = new javax.swing.JTextField();
        TfZiel = new javax.swing.JTextField();
        BtStart = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TaAusgabe = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TfZahl.setText("Scheibenanzahl");

        TfStart.setText("Start");

        TfMitte.setText("Mitte");

        TfZiel.setText("Ziel");

        BtStart.setText("Start");
        BtStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtStartActionPerformed(evt);
            }
        });

        TaAusgabe.setColumns(20);
        TaAusgabe.setRows(5);
        TaAusgabe.setText("4\n321\n1\n");
        jScrollPane1.setViewportView(TaAusgabe);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtStart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TfZahl, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(TfStart, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(TfMitte, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(TfZiel, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(TfZahl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TfStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TfMitte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TfZiel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(BtStart)
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtStartActionPerformed
        double zahl;
        String zahlStr;

        zahlStr = TfZahl.getText();
        zahl = Double.parseDouble(zahlStr);

        tuerme.put("a", TfStart.getText());
        tuerme.put("a", TfMitte.getText());
        tuerme.put("a", TfZiel.getText());

        umbauen(zahl, "a", "b", "c");
    }//GEN-LAST:event_BtStartActionPerformed

    public void umbauen(double zahl, String quelle, String temp, String ziel) {
        if (zahl > 0) {
            umbauen(zahl - 1, quelle, ziel, temp);

            String quelleString = tuerme.get(quelle);
            String scheibe = quelleString.substring(quelleString.length() - 1);
            quelleString = quelleString.substring(0, quelleString.length() - 1);
            tuerme.put(quelle, quelleString);

            String zielString = tuerme.get(ziel);
            zielString = zielString.concat(scheibe);
            tuerme.put(ziel, zielString);

            umbauen(zahl - 1, temp, ziel, quelle);
        }
        System.out.println(tuerme);
//    if size > 0:
//        versetze(size-1, quelle=quelle, ziel=temp, temp=ziel)
//        quelle.pop()
//        ziel.push()
//        versetze(size-1, quelle=temp, ziel=ziel, temp=quelle)
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtStart;
    private javax.swing.JTextArea TaAusgabe;
    private javax.swing.JTextField TfMitte;
    private javax.swing.JTextField TfStart;
    private javax.swing.JTextField TfZahl;
    private javax.swing.JTextField TfZiel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
