/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minotaurus;

/**
 *
 * @author NB
 */
public class Formular extends javax.swing.JFrame {

    private Minotaurus minotaurus;

    /**
     * Creates new form Formular
     */
    public Formular() {
        initComponents();
        minotaurus = new Minotaurus();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btTiefensuche1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btErzeugen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAusgabe = new javax.swing.JTextArea();
        btTiefensuche = new javax.swing.JButton();
        tfStart = new javax.swing.JTextField();
        tfZiel = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btBreitensuche = new javax.swing.JButton();
        btDijkstra = new javax.swing.JButton();

        btTiefensuche1.setText("Tiefensuche");
        btTiefensuche1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTiefensuche1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setText("Das Labyrinth des Daedalus");

        btErzeugen.setText("Labyrinth erzeugen");
        btErzeugen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btErzeugenActionPerformed(evt);
            }
        });

        taAusgabe.setColumns(20);
        taAusgabe.setRows(5);
        jScrollPane1.setViewportView(taAusgabe);

        btTiefensuche.setText("Tiefensuche");
        btTiefensuche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTiefensucheActionPerformed(evt);
            }
        });

        tfStart.setText("START");

        tfZiel.setText("ZIEL");

        jButton1.setText("Eulerweg möglich?");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btBreitensuche.setText("Breitensuche");
        btBreitensuche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBreitensucheActionPerformed(evt);
            }
        });

        btDijkstra.setText("Dijkstra");
        btDijkstra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDijkstraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel1)
                        .addGap(0, 43, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btErzeugen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btTiefensuche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfStart)
                            .addComponent(tfZiel)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btBreitensuche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btDijkstra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 35, Short.MAX_VALUE)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btErzeugen)
                        .addGap(36, 36, 36)
                        .addComponent(btTiefensuche)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btBreitensuche)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btDijkstra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(58, 58, 58)
                        .addComponent(tfStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfZiel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btErzeugenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btErzeugenActionPerformed
        taAusgabe.setText("");
        minotaurus = new Minotaurus();
        taAusgabe.append(minotaurus.graphToString());
    }//GEN-LAST:event_btErzeugenActionPerformed

    private void btTiefensucheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTiefensucheActionPerformed
        String start, ziel;
        start = tfStart.getText();
        ziel = tfZiel.getText();
        taAusgabe.setText("");
        taAusgabe.append(minotaurus.tiefensuche(start, ziel));
    }//GEN-LAST:event_btTiefensucheActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (minotaurus.hatEulerweg()) {
            taAusgabe.append("Ein Eulerweg ist möglich!");
        } else {
            taAusgabe.append("Ein Eulerweg ist NICHT möglich!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btTiefensuche1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTiefensuche1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btTiefensuche1ActionPerformed

    private void btBreitensucheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBreitensucheActionPerformed
        String start, ziel;
        start = tfStart.getText();
        ziel = tfZiel.getText();
        taAusgabe.setText("");
        taAusgabe.append(minotaurus.breitensuche(start, ziel));
    }//GEN-LAST:event_btBreitensucheActionPerformed

    private void btDijkstraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDijkstraActionPerformed
        String start, ziel;
        start = tfStart.getText();
        ziel = tfZiel.getText();
        taAusgabe.setText("");
        taAusgabe.append(minotaurus.dijkstra(start, ziel));
    }//GEN-LAST:event_btDijkstraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formular.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formular.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formular.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formular.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBreitensuche;
    private javax.swing.JButton btDijkstra;
    private javax.swing.JButton btErzeugen;
    private javax.swing.JButton btTiefensuche;
    private javax.swing.JButton btTiefensuche1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taAusgabe;
    private javax.swing.JTextField tfStart;
    private javax.swing.JTextField tfZiel;
    // End of variables declaration//GEN-END:variables
}
